### ISSUE TITLE
ACT score calculator down?

### ISSUE THREAD

**Issue by PathwayPrep** [WeGoToMars/WeGoToMars.github.io#6]
The ACT score calculator is not working, nor is the configure curves button functioning. Thanks for looking into it!

**Comment by WeGoToMars** [comment]
Oops, it looks like I made a one-letter typo in a commit (222b2333e912507f829a566e4caefdb9b87491c7) 10 days ago. It's fixed now: 1ccda3c75ab806eedb0f4054083040d123a6f07e and 11d5b5384f01992f705de4962a7b84dfae23b6d9. 
I don't really support the ACT calculator due to a low user base. @PathwayPrep, thank you for catching it!
